### ISSUE TITLE
use @soroban-react library

### ISSUE THREAD

**Issue by esteblock** [altugbakan/sorodogs#1]
Hello @altugbakan  , how are you?
I see that you are using a lot of functions that are included in the @soroban-react library.
Would you like to move into use the library instead? If you say yes I can make the transition and offer a PR!

**Comment by altugbakan** [comment]
Hey!

Thank you for the library functions. I used just parts of the library for custom user flow, as I needed more precise control like non-automatic login prompt.

I’m not sure if I will be improving upon this project, so you don’t need to spend time on this.

Thanks!
